
# travis config

dist: trusty
language: r
sudo: required
cache: packages

addons:
  apt:
    packages:
      - libxml2-dev

r:
 - release
 - oldrel
 - devel


before_install:
  - R -e "install.packages(c('tinytest','stringdist','knitr','roxygen2','pkgload'))"
  - make doc
  - cd ./pkg

r_packages:
  - covr
  - rmarkdown


after_success:
  - Rscript -e 'library(covr);coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change


